# Generated by Django 3.1.2 on 2020-10-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('character_id', models.IntegerField()),
                ('character_name', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
